import React from 'react';

import HeartsAce from '../../assets/cards/HeartsAce.png';
import Hearts2 from '../../assets/cards/Hearts2.png';
import Hearts3 from '../../assets/cards/Hearts3.png';
import Hearts4 from '../../assets/cards/Hearts4.png';
import Hearts5 from '../../assets/cards/Hearts5.png';
import Hearts6 from '../../assets/cards/Hearts6.png';
import Hearts7 from '../../assets/cards/Hearts7.png';
import Hearts8 from '../../assets/cards/Hearts8.png';
import Hearts9 from '../../assets/cards/Hearts9.png';
import Hearts10 from '../../assets/cards/Hearts10.png';
import HeartsJack from '../../assets/cards/HeartsJack.png';
import HeartsQueen from '../../assets/cards/HeartsQueen.png';
import HeartsKing from '../../assets/cards/HeartsKing.png';
import SpadesAce from '../../assets/cards/SpadesAce.png';
import Spades2 from '../../assets/cards/Spades2.png';
import Spades3 from '../../assets/cards/Spades3.png';
import Spades4 from '../../assets/cards/Spades4.png';
import Spades5 from '../../assets/cards/Spades5.png';
import Spades6 from '../../assets/cards/Spades6.png';
import Spades7 from '../../assets/cards/Spades7.png';
import Spades8 from '../../assets/cards/Spades8.png';
import Spades9 from '../../assets/cards/Spades9.png';
import Spades10 from '../../assets/cards/Spades10.png';
import SpadesJack from '../../assets/cards/SpadesJack.png';
import SpadesQueen from '../../assets/cards/SpadesQueen.png';
import SpadesKing from '../../assets/cards/SpadesKing.png';
import ClubsAce from '../../assets/cards/ClubsAce.png';
import Clubs2 from '../../assets/cards/Clubs2.png';
import Clubs3 from '../../assets/cards/Clubs3.png';
import Clubs4 from '../../assets/cards/Clubs4.png';
import Clubs5 from '../../assets/cards/Clubs5.png';
import Clubs6 from '../../assets/cards/Clubs6.png';
import Clubs7 from '../../assets/cards/Clubs7.png';
import Clubs8 from '../../assets/cards/Clubs8.png';
import Clubs9 from '../../assets/cards/Clubs9.png';
import Clubs10 from '../../assets/cards/Clubs10.png';
import ClubsJack from '../../assets/cards/ClubsJack.png';
import ClubsQueen from '../../assets/cards/ClubsQueen.png';
import ClubsKing from '../../assets/cards/ClubsKing.png';
import DiamondsAce from '../../assets/cards/DiamondsAce.png';
import Diamonds2 from '../../assets/cards/Diamonds2.png';
import Diamonds3 from '../../assets/cards/Diamonds3.png';
import Diamonds4 from '../../assets/cards/Diamonds4.png';
import Diamonds5 from '../../assets/cards/Diamonds5.png';
import Diamonds6 from '../../assets/cards/Diamonds6.png';
import Diamonds7 from '../../assets/cards/Diamonds7.png';
import Diamonds8 from '../../assets/cards/Diamonds8.png';
import Diamonds9 from '../../assets/cards/Diamonds9.png';
import Diamonds10 from '../../assets/cards/Diamonds10.png';
import DiamondsJack from '../../assets/cards/DiamondsJack.png';
import DiamondsQueen from '../../assets/cards/DiamondsQueen.png';
import DiamondsKing from '../../assets/cards/DiamondsKing.png';
import Back from '../../assets/cards/blue_back.png';

const card = (props) => {
    let card = null;
    if (props.card === 'HeartsAce') card = HeartsAce;
    if (props.card === 'Hearts2') card = Hearts2;
    if (props.card === 'Hearts3') card = Hearts3;
    if (props.card === 'Hearts4') card = Hearts4;
    if (props.card === 'Hearts5') card = Hearts5;
    if (props.card === 'Hearts6') card = Hearts6;
    if (props.card === 'Hearts7') card = Hearts7;
    if (props.card === 'Hearts8') card = Hearts8;
    if (props.card === 'Hearts9') card = Hearts9;
    if (props.card === 'Hearts10') card = Hearts10;
    if (props.card === 'HeartsJack') card = HeartsJack;
    if (props.card === 'HeartsQueen') card = HeartsQueen;
    if (props.card === 'HeartsKing') card = HeartsKing;
    if (props.card === 'SpadesAce') card = SpadesAce;
    if (props.card === 'Spades2') card = Spades2;
    if (props.card === 'Spades3') card = Spades3;
    if (props.card === 'Spades4') card = Spades4;
    if (props.card === 'Spades5') card = Spades5;
    if (props.card === 'Spades6') card = Spades6;
    if (props.card === 'Spades7') card = Spades7;
    if (props.card === 'Spades8') card = Spades8;
    if (props.card === 'Spades9') card = Spades9;
    if (props.card === 'Spades10') card = Spades10;
    if (props.card === 'SpadesJack') card = SpadesJack;
    if (props.card === 'SpadesQueen') card = SpadesQueen;
    if (props.card === 'SpadesKing') card = SpadesKing;
    if (props.card === 'ClubsAce') card = ClubsAce;
    if (props.card === 'Clubs2') card = Clubs2;
    if (props.card === 'Clubs3') card = Clubs3;
    if (props.card === 'Clubs4') card = Clubs4;
    if (props.card === 'Clubs5') card = Clubs5;
    if (props.card === 'Clubs6') card = Clubs6;
    if (props.card === 'Clubs7') card = Clubs7;
    if (props.card === 'Clubs8') card = Clubs8;
    if (props.card === 'Clubs9') card = Clubs9;
    if (props.card === 'Clubs10') card = Clubs10;
    if (props.card === 'ClubsJack') card = ClubsJack;
    if (props.card === 'ClubsQueen') card = ClubsQueen;
    if (props.card === 'ClubsKing') card = ClubsKing;
    if (props.card === 'DiamondsAce') card = DiamondsAce;
    if (props.card === 'Diamonds2') card = Diamonds2;
    if (props.card === 'Diamonds3') card = Diamonds3;
    if (props.card === 'Diamonds4') card = Diamonds4;
    if (props.card === 'Diamonds5') card = Diamonds5;
    if (props.card === 'Diamonds6') card = Diamonds6;
    if (props.card === 'Diamonds7') card = Diamonds7;
    if (props.card === 'Diamonds8') card = Diamonds8;
    if (props.card === 'Diamonds9') card = Diamonds9;
    if (props.card === 'Diamonds10') card = Diamonds10;
    if (props.card === 'DiamondsJack') card = DiamondsJack;
    if (props.card === 'DiamondsQueen') card = DiamondsQueen;
    if (props.card === 'DiamondsKing') card = DiamondsKing;
    if (props.card === 'Back') card = Back;

    return (
        <img src={card} alt="" />
    )
};

export default card;